version: '3'
services:
  kafka:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: 0.0.0.0
      ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
      - "2181:2181"
  scylla:
    image: scylladb/scylla
    ports:
      - "7000:7000"
      - "9160:9160"
      - "9180:9180"
      - "10000:10000"
      - "9042:9042"
      